<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="org.emdcs.test.partsordering.CSOOrderingTest" tests="4" time="121.880" ignored="0" failures="0" timestamp="02 Aug 2017 06:05:26 GMT" skipped="0" hostname="INHD0883" errors="1">
  <testcase name="Verifypartsinquiry" time="28.766" classname="org.emdcs.test.partsordering.CSOOrderingTest">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;...&gt; but was:&lt;...1&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...> but was:<...1>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.emdcs.test.partsordering.CSOOrderingTest.Verifypartsinquiry(CSOOrderingTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- Verifypartsinquiry -->
  <testcase name="VerifyAddAdditionalParts" time="27.175" classname="org.emdcs.test.partsordering.CSOOrderingTest"/>
  <testcase name="VerifyCSOPartsReset" time="23.200" classname="org.emdcs.test.partsordering.CSOOrderingTest"/>
  <testcase name="VerifyCSOpartsOrdering" time="42.739" classname="org.emdcs.test.partsordering.CSOOrderingTest"/>
</testsuite> <!-- org.emdcs.test.partsordering.CSOOrderingTest -->
